# Generated by Django 5.0.5 on 2024-05-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdv_stutent', models.CharField(max_length=35)),
                ('rdv_instructor', models.CharField(max_length=35)),
                ('rdv_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=22, unique=True)),
                ('email', models.EmailField(max_length=35, unique=True)),
                ('password', models.CharField(max_length=35)),
                ('role', models.IntegerField(default=1)),
            ],
        ),
    ]
