# Generated by Django 5.0.5 on 2024-05-28 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDrivingSchool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdv_date', models.DateTimeField()),
                ('title', models.CharField(max_length=45)),
                ('rdv_member', models.ManyToManyField(related_name='planning_hours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
